package Modelo;
// Generated 12-ago-2018 12:10:52 by Hibernate Tools 4.3.1



/**
 * Helado generated by hbm2java
 */
public class Helado  implements java.io.Serializable {


     private Integer idHelado;
     private String sabor;
     private String ruta;
     private Integer cantidad;

    public Helado() {
    }

    public Helado(String sabor, String ruta, Integer cantidad) {
       this.sabor = sabor;
       this.ruta = ruta;
       this.cantidad = cantidad;
    }
   
    public Integer getIdHelado() {
        return this.idHelado;
    }
    
    public void setIdHelado(Integer idHelado) {
        this.idHelado = idHelado;
    }
    public String getSabor() {
        return this.sabor;
    }
    
    public void setSabor(String sabor) {
        this.sabor = sabor;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


