package Modelo;
// Generated 12-ago-2018 12:10:52 by Hibernate Tools 4.3.1



/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private String helado;
     private Integer cantidad;
     private Double importe;
     private String fecha;

    public Venta() {
    }

    public Venta(String helado, Integer cantidad, Double importe, String fecha) {
       this.helado = helado;
       this.cantidad = cantidad;
       this.importe = importe;
       this.fecha = fecha;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public String getHelado() {
        return this.helado;
    }
    
    public void setHelado(String helado) {
        this.helado = helado;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


